import React, { useState } from 'react';

export function StoryModal() {
  const [isOpen, setIsOpen] = useState(false);
  const [isMuted, setIsMuted] = useState(true);

  const toggleMute = () => {
    setIsMuted(!isMuted);
  };

  const closeModal = () => {
    setIsOpen(false);
  };

  return (
    <div className="box-border">
      <div className="md:aspect-auto md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="static h-auto opacity-100 transform-none w-auto z-auto rounded-none left-auto bottom-auto md:fixed md:aspect-auto md:h-[266.667px] md:opacity-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-y-2.5 md:w-[150px] md:z-[2147483647] md:[mask-position:0%] md:bg-left-top md:p-1 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[15px] md:left-[calc(0%_+_10px)] md:bottom-[calc(0%_+_10px)]">
          <button 
            type="button" 
            aria-label="Play Story for PizzaCosy" 
            className="static text-black text-[13.3333px] bg-zinc-100 h-auto leading-[normal] text-center w-auto font-arial md:[mask-image:url(data:image/svg+xml;base64,%20PHN2ZyB2aWV3Qm94PSIwIDAgOSAxNiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICAgIDxwYXRoIGQ9Ik0gMC45IDAgTCA4LjEgMCBDIDguOCAwIDkgMC4yIDkgMC45IEwgOSAxNS4xIEMgOSAxNS44IDguOCAxNiA4LjEgMTYgTCAwLjkgMTYgQyAuMiAxNiAwIDE1LjggMCAxNS4xIEwgMCAuOSBDIDAgLjIgLjIgMCAuOSAwIi8+Cjwvc3ZnPgo=)] md:relative md:aspect-auto md:bg-transparent md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:p-0 md:scroll-m-0 md:scroll-p-[auto]"
            onClick={() => setIsOpen(true)}
          >
            <div className="static h-auto object-fill w-auto md:relative md:aspect-auto md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
              <video src="https://videos.join-stories.com/optimized/mp4/short-sd-pizza-cosy__2d9cf8a0-66ce-4b50-9a67-320b771e2eb3.mp4" className="block h-auto object-contain align-middle w-auto md:aspect-auto md:inline md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></video>
            </div>
            <div className="static rounded-none inset-auto md:absolute md:aspect-auto md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:border-neutral-900 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[10px] md:border-[5px] md:border-solid md:inset-0"></div>
          </button>
          <div className="static bg-none bg-repeat bg-auto h-auto w-auto right-auto top-auto md:absolute md:aspect-auto md:bg-[url(data:image/svg+xml;base64,PHN2ZyB2aWV3Qm94PSIwIDAgMTAwIDEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICA8Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI1MCIgZmlsbD0iIzAwMCIvPgogIDxwYXRoIGQ9Ik0gMjUgMzAgTCAzMCAyNSBMIDUwIDQ1IEwgNzAgMjUgTCA3NSAzMCBMIDU1IDUwIEwgNzUgNzAgTCA3MCA3NSBMIDUwIDU1IEwgMzAgNzUgTCAyNSA3MCBMIDQ1IDUwIFoiIGZpbGw9IiNGRkYiIC8+Cjwvc3ZnPgo=)] md:bg-no-repeat md:bg-contain md:h-5 md:overscroll-x-auto md:overscroll-y-auto md:right-[-5px] md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:top-[-5px] md:w-5 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></div>
        </div>
        <div className="static z-auto inset-auto md:fixed md:aspect-auto md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[2147483646] md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
        <div className="static h-auto w-auto z-auto rounded-none left-auto bottom-auto md:fixed md:aspect-auto md:h-[640px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[360px] md:z-[2147483646] md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-[20px] md:left-[calc(0%_+_10px)] md:bottom-5">
          <div className="box-border min-h-[auto] min-w-[auto] md:box-content md:min-h-0 md:min-w-0">
            <div className="static bg-transparent box-content block opacity-100 z-auto inset-auto md:fixed md:aspect-auto md:bg-black/70 md:box-border md:hidden md:opacity-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[2147483647] md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:inset-0"></div>
            <div className="static box-content block h-auto opacity-100 w-auto z-auto left-auto top-auto md:fixed md:aspect-auto md:box-border md:hidden md:h-full md:opacity-0 md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-[2147483647] md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:top-0">
              <div role="dialog" className="static text-base box-content h-auto leading-[normal] w-auto z-auto left-auto top-auto md:absolute md:text-[9.5952px] md:aspect-auto md:box-border md:h-full md:leading-[14.3928px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-0 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:top-0">
                <div className="static [align-items:normal] shadow-none box-content block h-auto justify-normal w-auto left-auto top-auto md:absolute md:items-center md:aspect-auto md:shadow-[rgba(0,0,0,0.25)_0px_3.83808px_16.3118px_0px] md:box-border md:flex md:h-[640px] md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[359.82px] md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-2/4 md:top-2/4">
                  <video aria-label="PizzaCosy" className="static bg-transparent box-content h-auto align-middle w-auto left-auto top-auto md:absolute md:aspect-auto md:bg-neutral-900 md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:top-0"></video>
                  <div className="static box-content h-auto w-auto z-auto left-auto top-auto md:absolute md:aspect-auto md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-10 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:top-0"></div>
                  <div className="static [align-items:normal] box-content block flex-row h-auto justify-normal w-auto z-auto left-auto top-auto md:absolute md:items-stretch md:aspect-auto md:box-border md:flex md:flex-col md:h-full md:justify-start md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-20 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:top-0">
                    <div className="[align-items:normal] bg-none box-content block h-auto justify-normal p-0 md:items-center md:aspect-auto md:bg-[linear-gradient(0deg,rgba(0,0,0,0)_6.99%,rgba(0,0,0,0.5)_163.32%)] md:box-border md:flex md:h-[73.8831px] md:justify-between md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:pl-[12.4738px] md:pr-[8.63568px] md:pt-[21.1094px] md:pb-[13.4333px] md:scroll-m-0 md:scroll-p-[auto]">
                      <div className="[align-items:normal] box-content gap-x-[normal] block max-w-none gap-y-[normal] z-auto md:items-center md:aspect-auto md:box-border md:gap-x-[9.5952px] md:flex md:max-w-[85%] md:overscroll-x-auto md:overscroll-y-auto md:gap-y-[9.5952px] md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-40 md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <img 
                          src="https://c.animaapp.com/menjgxnroMJDqo/assets/video-thumbnail-pizza-cosy__2d9cf8a0-66ce-4b50-9a67-320b771e2eb3.jpg" 
                          alt="Story Cover - PizzaCosy" 
                          className="bg-transparent bg-repeat bg-auto shadow-none box-content h-auto min-h-0 min-w-0 object-fill align-middle w-auto rounded-none md:aspect-auto md:bg-neutral-300 md:bg-no-repeat md:bg-cover md:shadow-[rgba(0,0,0,0.19)_0px_0px_4.50975px_0px] md:box-border md:h-[35.5023px] md:min-h-[35.5023px] md:min-w-[35.5023px] md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-[35.5023px] md:[mask-position:0%] md:bg-center md:scroll-m-0 md:scroll-p-[auto] md:rounded-[39.3403px]" 
                        />
                        <h1 className="text-black text-[32px] font-bold box-content block leading-[normal] mb-0 pb-0 font-times md:text-white md:text-[13.4333px] md:font-semibold md:aspect-auto md:box-border md:flow-root md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:-mb-0.5 md:pb-0.5 md:scroll-m-0 md:scroll-p-[auto] md:font-montserrat_600">PizzaCosy</h1>
                      </div>
                      <button 
                        aria-label="Close the story feed" 
                        className="text-black bg-zinc-100 inline-block h-auto leading-[normal] text-center w-auto z-auto rounded-none font-arial md:aspect-auto md:bg-transparent md:block md:h-[40.2999px] md:leading-[0px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[40.2999px] md:z-50 md:[mask-position:0%] md:bg-left-top md:p-0 md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"
                        onClick={closeModal}
                      >
                        <img src="https://c.animaapp.com/menjgxnroMJDqo/assets/icon-2.svg" alt="Icon" className="box-content block h-auto align-middle w-auto md:aspect-auto md:box-border md:inline md:h-[15.3523px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-[15.3523px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
                        <p className="box-content block my-0 md:aspect-auto md:box-border md:hidden md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:my-[9.5952px] md:scroll-m-0 md:scroll-p-[auto]">Close</p>
                      </button>
                    </div>
                    <div className="self-auto box-content block flex-row w-auto mr-0 md:self-end md:aspect-square md:box-border md:flex md:flex-col md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[40.2999px] md:[mask-position:0%] md:bg-left-top md:mr-[8.63568px] md:scroll-m-0 md:scroll-p-[auto]">
                      <button 
                        aria-label="Mute the story" 
                        className="text-black [align-items:normal] bg-zinc-100 inline-block h-auto justify-normal leading-[normal] text-center w-auto z-auto mb-0 rounded-none font-arial md:items-center md:aspect-auto md:backdrop-blur-[6.5px] md:bg-black/30 md:flex md:h-[40.2999px] md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-[40.2999px] md:z-40 md:[mask-position:0%] md:bg-left-top md:mb-[9.5952px] md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]"
                        onClick={toggleMute}
                      >
                        <img src="https://c.animaapp.com/menjgxnroMJDqo/assets/icon-3.svg" alt="Icon" className="box-content h-auto align-middle w-auto md:aspect-auto md:box-border md:h-[24.9475px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-[24.9475px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
                        <p className="box-content block my-0 md:aspect-auto md:box-border md:hidden md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:my-[9.5952px] md:scroll-m-0 md:scroll-p-[auto]">{isMuted ? 'Unmute' : 'Mute'}</p>
                      </button>
                    </div>
                  </div>
                  <div className="static box-content h-auto w-auto z-auto left-auto top-auto md:absolute md:aspect-auto md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-[21] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:top-0">
                    <div className="static [align-items:normal] box-content block m-0 top-auto inset-x-auto md:absolute md:items-center md:aspect-auto md:box-border md:flex md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:mx-[8.05997px] md:my-[6.71664px] md:scroll-m-0 md:scroll-p-[auto] md:top-0 md:inset-x-0">
                      <div className="box-content basis-auto grow-0 z-auto md:aspect-auto md:box-border md:basis-[0%] md:grow md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:z-[1] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
                        <div className="static [align-items:normal] box-content block h-auto min-h-0 w-auto md:relative md:items-center md:aspect-auto md:box-border md:flex md:h-[1.43928px] md:min-h-[1.5px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]"></div>
                      </div>
                    </div>
                  </div>
                  <div className="static box-content h-auto w-auto z-auto left-auto top-auto md:absolute md:aspect-auto md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:z-[22] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-0 md:top-0"></div>
                </div>
                <div className="static [align-items:normal] box-content gap-x-[normal] block flex-row justify-normal gap-y-[normal] right-auto top-auto md:absolute md:items-center md:aspect-auto md:box-border md:gap-x-[20.6297px] md:flex md:flex-row-reverse md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:gap-y-[20.6297px] md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:right-[calc(50%_+_201.499px)] md:top-2/4">
                  <button aria-label="Go to previous chapter" className="text-black [align-items:normal] bg-zinc-100 inline-block h-auto justify-normal leading-[normal] text-center w-auto z-auto rounded-none font-arial md:items-center md:aspect-auto md:backdrop-blur-[6.5px] md:bg-white md:hidden md:h-12 md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-12 md:z-[1] md:[mask-position:0%] md:bg-left-top md:p-[3.83808px] md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%]">
                    <img src="https://c.animaapp.com/menjgxnroMJDqo/assets/icon-4.svg" alt="Icon" className="box-content block h-auto align-middle w-auto md:aspect-auto md:box-border md:inline md:h-[30px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-[30px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
                    <p className="box-content block my-0 md:aspect-auto md:box-border md:hidden md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:my-[9.5952px] md:scroll-m-0 md:scroll-p-[auto]">Previous Chapter</p>
                  </button>
                </div>
                <div className="static [align-items:normal] box-content gap-x-[normal] block justify-normal gap-y-[normal] left-auto top-auto md:absolute md:items-center md:aspect-auto md:box-border md:gap-x-[20.6297px] md:flex md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:gap-y-[20.6297px] md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:left-[calc(50%_+_201.499px)] md:top-2/4">
                  <button aria-label="Go to next chapter" className="text-black [align-items:normal] bg-zinc-100 inline-block h-auto justify-normal leading-[normal] opacity-100 text-center w-auto z-auto rounded-none left-auto font-arial md:items-center md:aspect-auto md:backdrop-blur-[6.5px] md:bg-white md:hidden md:h-12 md:justify-center md:opacity-[0.43] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-12 md:z-[1] md:[mask-position:0%] md:bg-left-top md:p-[3.83808px] md:scroll-m-0 md:scroll-p-[auto] md:rounded-[50%] md:left-1/4">
                    <img src="https://c.animaapp.com/menjgxnroMJDqo/assets/icon-4.svg" alt="Icon" className="box-content block h-auto align-middle w-auto md:aspect-auto md:box-border md:inline md:h-[30px] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-[30px] md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]" />
                    <p className="box-content block my-0 md:aspect-auto md:box-border md:hidden md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:my-[9.5952px] md:scroll-m-0 md:scroll-p-[auto]">Next Chapter</p>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <div className="absolute bg-white border-b-emerald-900 border-l-emerald-900 border-r-emerald-900 border-t-zinc-300 shadow-[rgba(0,0,0,0.3)_0px_2px_6px_0px] box-border hidden w-0 z-[1300000001] overflow-hidden rounded-sm border-t left-0 top-0 font-arial after:accent-auto after:bg-[url('https://maps.gstatic.com/mapfiles/api-3/images/powered-by-google-on-white3.png')] after:bg-right after:bg-no-repeat after:bg-size-[120px_14px] after:box-border after:text-emerald-900 after:block after:text-lg after:not-italic after:normal-nums after:font-normal after:h-[18px] after:tracking-[normal] after:leading-[27px] after:list-outside after:list-disc after:text-right after:indent-[0px] after:normal-case after:visible after:pr-px after:py-px after:border-separate after:font-arial"></div>
      <div className="absolute bg-white border-b-emerald-900 border-l-emerald-900 border-r-emerald-900 border-t-zinc-300 shadow-[rgba(0,0,0,0.3)_0px_2px_6px_0px] box-border hidden w-0 z-[1300000001] overflow-hidden rounded-sm border-t left-0 top-0 font-arial after:accent-auto after:bg-[url('https://maps.gstatic.com/mapfiles/api-3/images/powered-by-google-on-white3.png')] after:bg-right after:bg-no-repeat after:bg-size-[120px_14px] after:box-border after:text-emerald-900 after:block after:text-lg after:not-italic after:normal-nums after:font-normal after:h-[18px] after:tracking-[normal] after:leading-[27px] after:list-outside after:list-disc after:text-right after:indent-[0px] after:normal-case after:visible after:pr-px after:py-px after:border-separate after:font-arial"></div>
      <div className="absolute bg-white border-b-emerald-900 border-l-emerald-900 border-r-emerald-900 border-t-zinc-300 shadow-[rgba(0,0,0,0.3)_0px_2px_6px_0px] box-border hidden w-0 z-[1300000001] overflow-hidden rounded-sm border-t left-0 top-0 font-arial after:accent-auto after:bg-[url('https://maps.gstatic.com/mapfiles/api-3/images/powered-by-google-on-white3.png')] after:bg-right after:bg-no-repeat after:bg-size-[120px_14px] after:box-border after:text-emerald-900 after:block after:text-lg after:not-italic after:normal-nums after:font-normal after:h-[18px] after:tracking-[normal] after:leading-[27px] after:list-outside after:list-disc after:text-right after:indent-[0px] after:normal-case after:visible after:pr-px after:py-px after:border-separate after:font-arial"></div>
      <div className="absolute bg-white border-b-emerald-900 border-l-emerald-900 border-r-emerald-900 border-t-zinc-300 shadow-[rgba(0,0,0,0.3)_0px_2px_6px_0px] box-border hidden w-0 z-[1300000001] overflow-hidden rounded-sm border-t left-0 top-0 font-arial after:accent-auto after:bg-[url('https://maps.gstatic.com/mapfiles/api-3/images/powered-by-google-on-white3.png')] after:bg-right after:bg-no-repeat after:bg-size-[120px_14px] after:box-border after:text-emerald-900 after:block after:text-lg after:not-italic after:normal-nums after:font-normal after:h-[18px] after:tracking-[normal] after:leading-[27px] after:list-outside after:list-disc after:text-right after:indent-[0px] after:normal-case after:visible after:pr-px after:py-px after:border-separate after:font-arial"></div>
    </div>
  );
}
